name: CD
on:
  push:
    branches:
      - main
jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: flipday/backend

  update-dockerhub-image:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          source: "./docker-compose.yml"
          target: "docker-compose-back"
      
      - name: copy database via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          source: "./database"
          target: "docker-compose-back"

  execute-docker-compose-droplet:
    runs-on: ubuntu-latest
    needs: update-dockerhub-image

    steps:
      - name: Run docker-compose SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          script: | 
              cd docker-compose-back
              docker stop node_server
              docker container rm node_server
              docker rmi flipday/backend
              docker stop mariadb
              docker container rm mariadb
              docker rmi mariadb:10.5.6
              docker-compose up -d