name: Deploy Digital Ocean
on:
  push:
    #branches: [issue56]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP Digital Ocean
          key: ${{secrets.SSH_KEY}} # Private SSH KEY
          username: ${{ secrets.SSH_USERNAME }} # User of the server you use in SSH
          #First clone docker-compose and start.sh
          script: |
            mkdir pickauto
            cd pickauto
            rm -rf motor-services-backend
            git clone git@github.com:fullstacktf/motor-services-backend.git
            cd motor-services-backend
            ./start.sh
            echo 'Deployment successfully to digital ocean' 